apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: dev
type: kubernetes.io/basic-auth
stringData:
  username: root      # required field for kubernetes.io/basic-auth
  password: t0p-Secret # required field for kubernetes.io/basic-auth
  database: test